apiVersion: v2
appVersion: 0.1.0
description: Service Name
name: go-service-template
type: application
version: 0.1.0
dependencies:
  - name: starter-lib
    repository: "@lsk-helm-repo"
    version: ">=0.2,<1.0"
  - name: env-lib
    repository: "@lsk-helm-repo"
    version: ">=0.3,<1.0"
    import-values:
      - environmentConfig
